#!/usr/bin/env bash
# Build ua571-web for the browser and emit JS glue into web/pkg/
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TARGET="${TARGET:-wasm32-unknown-unknown}"
PROFILE_FLAG="${PROFILE_FLAG:---release}"
OUT_DIR="${OUT_DIR:-web/pkg}"
WASM_BINDGEN_VERSION="${WASM_BINDGEN_VERSION:-0.2.100}"

if ! command -v rustup >/dev/null; then
  echo "rustup required" >&2
  exit 1
fi

rustup target add "$TARGET" >/dev/null

need_bindgen=1
if command -v wasm-bindgen >/dev/null; then
  if wasm-bindgen --version 2>/dev/null | grep -Fq "${WASM_BINDGEN_VERSION}"; then
    need_bindgen=0
  else
    echo "wasm-bindgen $(wasm-bindgen --version 2>/dev/null || echo unknown) != ${WASM_BINDGEN_VERSION}; reinstalling..."
  fi
fi
if [[ "$need_bindgen" -eq 1 ]]; then
  echo "Installing wasm-bindgen-cli ${WASM_BINDGEN_VERSION}..."
  cargo install wasm-bindgen-cli --version "${WASM_BINDGEN_VERSION}" --locked --force
fi

echo "→ cargo build -p ua571-web --target $TARGET $PROFILE_FLAG --locked"
cargo build -p ua571-web --target "$TARGET" $PROFILE_FLAG --locked

if [[ "$PROFILE_FLAG" == "--release" ]]; then
  WASM_PATH="target/$TARGET/release/ua571_web.wasm"
else
  WASM_PATH="target/$TARGET/debug/ua571_web.wasm"
fi

mkdir -p "$OUT_DIR"
echo "→ wasm-bindgen → $OUT_DIR"
wasm-bindgen "$WASM_PATH" \
  --target web \
  --out-dir "$OUT_DIR" \
  --out-name ua571_web

# Cache-bust token for browsers/CDN (content hash of the wasm binary).
BUILD_ID="$(shasum -a 256 "$OUT_DIR/ua571_web_bg.wasm" | awk '{print substr($1,1,12)}')"
cat > web/build-id.js <<EOF
// Generated by scripts/build-web.sh — do not edit.
export const BUILD_ID = "${BUILD_ID}";
EOF
echo "→ build id ${BUILD_ID}"

echo "Done. Serve the web/ directory, e.g.:"
echo "  python3 -m http.server 8080 --directory web"
echo "  open http://localhost:8080"
